core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'), 
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

eshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from core.views import index

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('new', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

dashboard/models.py
from django.db import models

# Create your models here.

item/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def __str__(self) -> str:
        return self.name
    

class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, related_name="items", on_delete=models.CASCADE)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Items'

    def __str__(self) -> str:
        return self.name

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'type your username',
        'is_required': True,
        'class': 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'
    }))
        
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'name@company.com',
        'is_required': True,
        'class': 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': "••••••••",
        'is_required': True,
        'class': "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': "••••••••",
        'is_required': True,
        'class': "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
    }))


class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'type your username',
        'is_required': True,
        'class': 'bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': "••••••••",
        'is_required': True,
        'class': "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
    }))

item/forms.py
from django import forms

from .models import Item

INPUT_CLASS = "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'description', 'price', 'category', 'image')

        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASS
                }),
            'name': forms.TextInput(attrs={
                'placeholder': 'type your item name',
                'is_required': True,
                'class': INPUT_CLASS
                }),
            'description': forms.Textarea(attrs={
                'placeholder': 'type your item description',
                'is_required': True,
                'class': INPUT_CLASS
                }),
            'price': forms.NumberInput(attrs={
                'placeholder': 'enter your item price',
                'is_required': True,
                'class': INPUT_CLASS
                }),
            'image': forms.FileInput(attrs={
                'is_required': True,
                'class': INPUT_CLASS
                }),
        }

core/views.py
from django.shortcuts import render, redirect

from item.models import Category, Item

from .forms import SignupForm


def index(request):
    items = Item.objects.filter(is_sold=False)
    categories = Category.objects.all()
    return render(request, 'core/index.html', {'items': items, 'categories': categories})


def contact(request):
    return render(request, 'core/contact.html')


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            password1 = request.POST.get('password1')
            password2 = request.POST.get('password2')
            if password1 == password2:
                form.save()

            return redirect('/login')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {'form': form})

dashboard/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required

from item.models import Item

@login_required
def index(request):
    items = Item.objects.filter(created_by=request.user)

    return render(request, 'dashboard/index.html', {'items': items})

item/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect
from .models import Item
from .forms import NewItemForm


def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(
        category=item.category, is_sold=False).exclude(pk=pk)[0:3]

    return render(request, 'item/detail.html', {'item': item, "related_items": related_items})


@login_required
def new(request):
    if request.method == "POST":
        form = NewItemForm(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()

            return redirect('item:detail', pk=item.id)
    else:
        form = NewItemForm()

    return render(request, 'item/form.html', {'form': form, 'title': '📝New Item'})

@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()

    return redirect('dashboard:index')

core/templates/core/contact.html
{% extends "core/layout.html" %}

{% block title %}Contact{% endblock %}

{% block content %}
    <h1>Contact page</h1>
{% endblock %}

core/templates/core/index.html
{% extends "core/layout.html" %} {% block title %}🏠 Home{% endblock %} 

{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-lg">
  <h2 class="mb-12 text-3xl font-semibold text-teal-500 text-center">
    ✨ Newest Items
  </h2>
  <div class="grid grid-cols-3 gap-3">
    {% for item in items %}
    <div class="w-[80%]">
      <a href="{% url 'item:detail' item.id %}">
        <div class="">
          <img
            src="{{ item.image.url }}"
            alt="{{ item.name }}"
            class="rounded-t-xl shadow-md h-96 w-full object-fit p-4 bg-white"
          />
        </div>
        <div class="p-6 rounded-b-xl bg-gray-200">
          <div class="text-lg">🛒{{ item.name }}</div>
          <div>🏷️Price: {{ item.price }}₹</div>
        </div>
      </a>
    </div>
    {% endfor %}
  </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-lg">
  <h2 class="mb-12 text-3xl font-semibold text-teal-500 text-center">
    🛍️ Categories
  </h2>
  <div class="grid grid-cols-3 gap-3">
    {% for category in categories %}
    <div class="w-[80%]">
      <a href="#">
        <div class="p-6 rounded-xl bg-gray-200">
          <div class="text-lg">{{ category.name }}</div>
          <div>🔖{{ category.items.count }} items</div>
        </div>
      </a>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

core/templates/core/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="https://img.icons8.com/3d-fluency/94/shopping-bag.png">
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
      tailwind.config = {
        theme: {
          extend: {
            colors: {
              primary: {"50":"#eff6ff","100":"#dbeafe","200":"#bfdbfe","300":"#93c5fd","400":"#60a5fa","500":"#3b82f6","600":"#2563eb","700":"#1d4ed8","800":"#1e40af","900":"#1e3a8a","950":"#172554"}
            }
          }
        }
      }
    </script>
    <title>{% block title %}{% endblock %} | E-Shope</title>
  </head>

  <body>
    {% comment %} Top Navigation Bar {% endcomment %}
    <nav class="bg-gray-800 p-4 flex justify-between items-center">
      <div class="flex gap-2">
        <img width="32" height="24" src="https://img.icons8.com/3d-fluency/94/shopping-bag.png" alt="shopping-bag"/>    
        <a href="/" class="text-2xl font-semibold text-red-500"> E-Shope </a>
      </div>
      <div class="gap-2">
        <a href="{% url 'item:new' %}" class="text-teal-500 hover:text-white border-red-500 hover:border-[0.5px] rounded-md px-3 py-2 text-md font-medium">New Items</a>
        <a href="#" class="text-teal-500 hover:text-white border-red-500 hover:border-[0.5px] rounded-md px-3 py-2 text-md font-medium">Browse</a>

        {% if request.user.is_authenticated %}
            <a href="{% url 'core:login' %}" class="text-teal-500 hover:text-white bg-gray-900 hover:bg-gray-800 border-red-500 hover:border-[0.5px] rounded-md px-3 py-2 text-md font-medium">Inbox</a>
            <a href="{% url 'dashboard:index' %}" class="text-teal-500 hover:text-white bg-gray-900 hover:bg-gray-800 border-red-500 hover:border-[0.5px] rounded-md px-3 py-2 text-md font-medium">Dashbord</a>
        {% else %}
            <a href="{% url 'core:login' %}" class="text-teal-500 hover:text-white bg-gray-900 hover:bg-gray-800 border-red-500 hover:border-[0.5px] rounded-md px-3 py-2 text-md font-medium">Log in</a>
            <a href="{% url 'core:signup' %}" class="text-teal-500 hover:text-white bg-gray-900 hover:bg-gray-800 border-red-500 hover:border-[0.5px] rounded-md px-3 py-2 text-md font-medium">Sign up</a>
        {% endif %}
      </div>
    </nav>
    <div class="px-6 min-h-fit w-full mt-2 mb-6">{% block content %}{% endblock %}</div>

    {% comment %} Bottom Fotter {% endcomment %}
    <br/>
    <footer class="mt-6 bottom-0 bg-gray-800 p-4 flex justify-center items-center">
        <span class="text-white text-md">
            Made with ❣️ by <a href="http://github.com/JeelGajera" class="underline underline-offset-2 hover:text-teal-500" >Jeel Gajera</a>        </span>
    </footer>
  </body>
</html>

core/templates/core/login.html
{% extends 'core/layout.html' %} {% block title %}🔒Login{% endblock %} 

{% block content %}
<section class="bg-gray-200">
  <div
    class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0"
  >
    <div class="flex gap-2 mb-6">
      <img
        width="32"
        height="24"
        src="https://img.icons8.com/3d-fluency/94/shopping-bag.png"
        alt="shopping-bag"
      />
      <a href="/" class="text-3xl font-semibold text-red-500"> E-Shope </a>
    </div>
    <div
      class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700"
    >
      <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
        <h1
          class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white"
        >
          Login to E-Shope
        </h1>
        <form class="space-y-4 md:space-y-6" method="post" action=".">
          {% csrf_token %}

          <div>
            <label
              for="username"
              class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
              >Username</label
            >
            {{ form.username }}
          </div>
          <div>
            <label
              for="password"
              class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
              >Password</label
            >
            {{ form.password }}
          </div>

          {% if form.errors or form.non_field_errors %}
          <div class="mb-3 p-6 bg-red-500 rounded-xl text-white">
              {% for field in form %}
                  {{ field.errors }}
              {% endfor %}
          </div>
          {% endif %}

          <button
            type="submit"
            class="w-full text-white bg-primary-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800"
          >
            Login to account
          </button>
          <p class="text-sm font-light text-gray-500 dark:text-gray-400">
            Do not have an account?
            <a
              href="{% url 'core:signup' %}"
              class="font-medium text-primary-600 hover:underline dark:text-primary-500"
              >Signup here</a
            >
          </p>
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/layout.html' %} {% block title %}🔐Sign Up{% endblock %} 

{% block content %}
<section class="bg-gray-200">
  <div
    class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0"
  >
    <div class="flex gap-2 mb-6">
      <img
        width="32"
        height="24"
        src="https://img.icons8.com/3d-fluency/94/shopping-bag.png"
        alt="shopping-bag"
      />
      <a href="/" class="text-3xl font-semibold text-red-500"> E-Shope </a>
    </div>
    <div
      class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700"
    >
      <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
        <h1
          class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white"
        >
          Create and account
        </h1>
        <form class="space-y-4 md:space-y-6" method="post" action=".">
          {% csrf_token %}

          <div>
            <label
              for="username"
              class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
              >Username</label
            >
            {{ form.username }}
          </div>
          <div>
            <label
              for="email"
              class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
              >Your email</label
            >
            {{ form.email }}
          </div>
          <div>
            <label
              for="password"
              class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
              >Password</label
            >
            {{ form.password1 }}
          </div>
          <div>
            <label
              for="confirm-password"
              class="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
              >Confirm password</label
            >
            {{ form.password2 }}
          </div>

          {% if form.errors or form.non_field_errors %}
          <div class="mb-3 p-6 bg-red-500 rounded-xl text-white">
              {% for field in form %}
                  {{ field.errors }}
              {% endfor %}
          </div>
          {% endif %}

          <button
            type="submit"
            class="w-full text-white bg-primary-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800"
          >
            Create an account
          </button>
          <p class="text-sm font-light text-gray-500 dark:text-gray-400">
            Already have an account?
            <a
              href="{% url 'core:login' %}"
              class="font-medium text-primary-600 hover:underline dark:text-primary-500"
              >Login here</a
            >
          </p>
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock %}

dashboard/templates/dashboard/index.html
{% extends "core/layout.html" %} {% block title %}🛍️ Dashboard{% endblock %} 

{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-lg">
  <h2 class="mb-12 text-3xl font-semibold text-teal-500 text-center">
    ✨ My Items
  </h2>
  <div class="grid grid-cols-3 gap-3">
    {% for item in items %}
    <div class="w-[80%]">
      <a href="{% url 'item:detail' item.id %}">
        <div class="">
          <img
            src="{{ item.image.url }}"
            alt="{{ item.name }}"
            class="rounded-t-xl shadow-md h-96 w-full object-fit p-4 bg-white"
          />
        </div>
        <div class="p-6 rounded-b-xl bg-gray-200">
          <div class="text-lg">🛒{{ item.name }}</div>
          <div>🏷️Price: {{ item.price }}₹</div>
        </div>
      </a>
    </div>
    {% endfor %}
  </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-lg">
  <h2 class="mb-12 text-3xl font-semibold text-teal-500 text-center">
    🛍️ Categories
  </h2>
  <div class="grid grid-cols-3 gap-3">
    {% for category in categories %}
    <div class="w-[80%]">
      <a href="#">
        <div class="p-6 rounded-xl bg-gray-200">
          <div class="text-lg">{{ category.name }}</div>
          <div>🔖{{ category.items.count }} items</div>
        </div>
      </a>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

item/templates/item/detail.html
{% extends 'core/layout.html' %} 
{% block title %} {{ item.name}} {% endblock %}
{% block content %}
<div class="flex flex-col gap-2 item-center bg-gray-100">
  <div class="flex justify-center item-center">
  <div class="col-span-3 w-fit">
    {% if item.image %}
    <img
      src="{{ item.image.url }}"
      alt="{{ item.name }}"
      class="rounded-xl shadow-xl h-[70vh] w-fit object-cover p-4 bg-white m-2"
    />
    {% else %}
    <p>No image available</p>
    {% endif %}
  </div>
  <div class="flex-start flex-col justify-center item-center p-6">
    <h1
      class="mb-6 text-3xl font-semibold decoration-teal-500 underline underline-offset-2 text-red-500"
    >
      {{ item.name }}
    </h1>
    <p class="text-gray-500"><strong>🏷️Price: </strong>{{item.price}}₹</p>
    <p class="text-gray-500"><strong>📢Seller: </strong>{{item.created_by}}</p>
    {% if item.description %}
    <p class="text-gray-700">
      <strong>📜Description: </strong><br />{{item.description}}
    </p>
    {% endif %} 

    {% if request.user == item.created_by %}
      <div class="flex justify-center item-center gap-2">
        <a href="{% url 'item:delete' item.id %}">
          <button class="px-4 py-2 bg-teal-500 text-white rounded-lg shadow-lg hover:bg-red-600">
            🖊️ Edit
          </button>
        </a>
        <a href="{% url 'item:delete' item.id %}">
          <button class="px-4 py-2 bg-red-500 text-white rounded-lg shadow-lg hover:bg-red-600">
            🗑️Delete
          </button>
        </a>
      </div>
    {% endif %}
  </div>
  </div>

  {% if related_items %}
  <div class="mt-6 px-6 py-12 bg-gray-100 rounded-lg">
    <h2 class="mb-12 text-3xl font-semibold text-teal-500 text-center">
      ✨ Related Items
    </h2>
    <div class="grid grid-cols-3 gap-3 mb-1">
      {% for related_item in related_items %}
      <div class="w-fit h-fit">
        <a href="{% url 'item:detail' related_item.id %}">
          <div class="">
            {% if related_item.image %}
            <img
              src="{{ related_item.image.url }}"
              alt="{{ related_item.name }}"
              class="p-2 rounded-t-xl shadow-xl w-64 h-56 object-fit bg-white overflow-hidden"
            />
            {% else %}
            <p>No image available</p>
            {% endif %}
          </div>
          <div class="p-2 rounded-b-xl bg-gray-200 w-64">
            <div class="text-lg">🛒{{ related_item.name }}</div>
            <div>🏷️Price: {{ related_item.price }}₹</div>
          </div>
        </a>
      </div>
      {% endfor %}
    </div>
  </div>
  {% endif %} {% endblock %}
</div>

item/templates/item/form.html
{% extends 'core/layout.html' %} {% block title %}{{ title }}{% endblock %} 

{% block content %}
<section class="z-0">
  <div
    class="flex flex-col items-center justify-center px-6 py-8 mx-auto lg:py-0"
  >
    <div class="flex gap-2 mb-6">
      <img
        width="32"
        height="24"
        src="https://img.icons8.com/3d-fluency/94/shopping-bag.png"
        alt="shopping-bag"
      />
      <a href="/" class="text-3xl font-semibold text-red-500"> E-Shope </a>
    </div>
    <div
      class="w-full bg-gray-200 rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0"
    >
      <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
        <h1
          class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl"
        >
          {{ title }}
        </h1>
        <form
          class="space-y-4 md:space-y-6"
          method="post"
          action=""
          enctype="multipart/form-data"
        >
          {% csrf_token %}

          <div class="space-y-4">{{ form.as_p }}</div>

          {% if form.errors or form.non_field_errors %}
          <div class="mb-3 p-6 bg-red-500 rounded-xl text-white">
            {% for field in form %} {{ field.errors }} {% endfor %}
          </div>
          {% endif %}

          <button
            class="w-full text-white bg-primary-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-lg px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800"
          >
            Submit
          </button>
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock %}